import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AntdTheme from "@/providers/AntdTheme";
import Antd from "@/providers/AntdRegistry";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Safebite Application",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nextAuthSession = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <NextAuthProvider session={nextAuthSession}>
          <AntdTheme>
            <Antd>{children}</Antd>
          </AntdTheme>
        </NextAuthProvider>
      </body>
    </html>
  );
}
